source 'https://rubygems.org'

gem 'rails'
gem 'rspec-rails'
gem 'sqlite3'

group :development do
  gem 'spring'
end

group :test do
  gem 'database_cleaner'
  gem 'rails-controller-testing'
  gem 'capybara'
end
